import Entity from '../entity'

//车型
export default class Clasen extends Entity<number>{
    BrandAuto:number;//厂牌ID
    clasenName:string;//车型名称
    Cdt:Date;
    Cuser:number
    Mdt:Date
    Muser:number
    OverP_0_5:number
    OverP_1:number
    OverP_1_5:number
    OverP_2:number
    OverP_2_5:number
    OverP_3:number
    OverP_3_5:number
    OverP_4:number
    OverP_4_5:number
    OverP_5:number
    OverP_5_5:number
    OverP_6:number
    OverP_6_5:number
    OverP_7:number
    OverP_7_5:number
    OverP_8:number
    RateKM_0_5W:number
    RateKM_1W:number
    RateKM_1_5W:number
    RateKM_2W:number
    RateKM_2_5W:number
    RateKM_3W:number
    RateKM_3_5W:number
    RateKM_4W:number
    RateKM_4_5W:number
    RateKM_5W:number
    RateKM_5_5W:number
    RateKM_6W:number
    RateKM_6_5W:number
    RateKM_7W:number
    RateKM_7_5W:number
    RateKM_8W:number
    RateKM_8_5W:number
    RateKM_9W:number
    RateKM_9_5W:number
    RateKM_10W:number
    RateKM_10_5W:number
    RateKM_11W:number
    RateKM_11_5W:number
    RateKM_12W:number
    RateKM_12_5W:number
    RateKM_13W:number
    RateKM_13_5W:number
    RateKM_14W:number
    RateKM_14_5W:number
    RateKM_15W:number
    RateKM_15_5W:number
    RateKM_16W:number
    RateKM_16_5W:number
    RateKM_17W:number
    RateKM_17_5W:number
    RateKM_18W:number
    RateKM_18_5W:number
    RateKM_19W:number
    RateKM_19_5W:number
    RateKM_20W:number
    RateKM_20_5W:number
    RateKM_21W:number
    RateKM_21_5W:number
    RateKM_22W:number
    RateKM_22_5W:number
    RateKM_23W:number
    RateKM_23_5W:number
    RateKM_24W:number
    RateKM_24_5W:number
    RateKM_25W:number
    RateKM_25_5W:number
    RateKM_26W:number
    RateKM_26_5W:number
    RateKM_27W:number
    RateKM_27_5W:number
    RateKM_28W:number
    RateKM_28_5W:number
    RateKM_29W:number
    RateKM_29_5W:number
    RateKM_30W:number
    Memo:string
}