import Entity from '../entity'

export default class Insure2 extends Entity<number>{
    orderAuto:number;	//Order_Auto	bigint
    carBaseAuto:number;	//CarBase_Auto	bigint
    supplier:number;	//Supplier	bigint
    insureNo:string;	//InsureNo	nvarchar
    getPrice:number;	//GetPrice	decimal
    insureDisCount:number;	//InsureDisCount	decimal
    carTax:number;	//CarTax	decimal
    orgAmt:number;	//OrgAmt	decimal
    rateAmt:number;	//RateAmt	decimal
    finalAmt:number;	//FinalAmt	decimal
    realAmt:number; //RealAmt	decimal
    payAmt:number;	//PayAmt	decimal
    startDT:Date;	//StartDT	datetime2
    endDT:Date;	//EndDT	datetime2
    rescissionDT:Date;	//RescissionDT	datetime2
    isBusiness:number;	//IsBusiness	int
    year:number;	//第几年	int
    insIsRebates:number;	//交强险是否返利	int
    insRate:number;	///交强险返利率	nchar
    insReAmt:number;	//交强险返利金额	decimal
    insRemark:string;	//交强险返利备注	nvarchar
    insDIsRebates:number;	//商业险是否返利	int
    insDRate:string;	//InsDRate	nchar
    insDReAmt:number;	//商业险返利金额	decimal
    insDRemark:string;	//商业险返利备注	nvarchar
    Status:number;	//Status	int
    cuser:number;	//CUser	int
    cdt:Date;	//CDT	datetime2
    muser:number;	//MUSer	int
    mdt:Date;	//MDT	datetime2
    batch:number;	//请款批次	bigint
    trnType:number;	//TrnType	int
    trnDate:Date;	//TrnDate	datetime2
    insureLimit:number;	//InsureLimit	decimal
    insureType:number;	//InsureType	int
    insurePercnt:number;	//InsurePercnt	int
    detailAmt:number;	//DetailAmt	decimal
    offerAmt:number;	//OfferAmt	decimal
    insPAIRate:string;	//InsPAIRate	nvarchar
    creationTime:Date;	//CreationTime	datetime2
    creatorUserId:number;	//CreatorUserId	bigint
    lastModificationTime:Date;	//LastModificationTime	datetime2
    lastModifierUserId:number;	//LastModifierUserId	bigint
    isDeleted:number;	//IsDeleted	bit
    deleterUserId:number;	//DeleterUserId	bigint
    deletionTime:Date;	//DeletionTime	datetime2
}